### ISSUE TITLE
koop refactor breaks custom provider that uses cache \ cache catalog operations

### ISSUE THREAD

**Issue by ButchGis** [koopjs/koop-core#136]
https://github.com/koopjs/koop-core/blob/41a5695a983f5c8b357a0edc472d010f61ca421c/lib/provider-registration/create-model.js#L24
I have been trying to upgrade koop to newer versions and somewhere between 3.16 and 3.19 koop framework started adding ::data to the end of cache keys. I have a custom createKey function in my provider and up to 3.16 I could reliably update, append, or otherwise manipulate my cache. 
But with newer versions of koop I have many issues that all seem related to cache objects not found, or updated.
Looking through the code, I see that the return from createKey might be manipulated in other ways as well, addition of ::layer. 
The documents are not updated, or I missed the change, whats the new api?

previously I used cache.append with key = result of createKey now i think I must use createKey::data.

trying to avoid trial and error process ...

**Comment by haoliangyu** [comment]
Thanks for the report. This is likely to v3.17.2, where new cache keys were introduced to differentiate the cache for features and layers. We will take a look and get back to you soon.

**Comment by rgwozdz** [comment]
@ButchGis can you give some more details about your issues?  Are there any error logs or are you just seeing unexpected behavior?  Note that the in the cache-lookup block, the cache-plugin throws an error (which is handled) when a key is not found;  Presence of that error indicates Koop should use getData, but I think in debug mode the error is logged, which can be confusing - may lead you to think there is a problem, when errors are just part of the expected response from the cache plugin.

**Comment by ButchGis** [comment]
Rich,

its not issue with log. The cache object is not what's expected. The cached data ends up under key that has ::data appended to it.
so when i come along with custom routes or that access cache they never find the key. No appends, No updates are possible. I could append ::data to my key in my custom routes.

but I'm looking for clarity about when to that and if other key modification is necessary.


Butch
________________________________

**Comment by rgwozdz** [comment]
got it, thanks.

**Comment by haoliangyu** [comment]
Looks like a bug in koop-core. The `::data` suffix should be appended to the default key and the custom key.

**Comment by haoliangyu** [comment]
I investigate more in this issue.

In https://github.com/koopjs/koop-core/blob/master/lib/provider-registration/create-model.js, it adds the internal key suffix `::data`, `::layer`, and `::catalog`. The suffix is used to differentiate the cache for layer data, layer metadata, and catalog metadata. It is added without the notice of the user or developer and is only meant for internal use. However, if the user defines a custom key generator, it will still add the suffix to the generated key and the user is unable to manipulate the cache object with the API https://github.com/koopjs/koop-core/blob/master/lib/datasets/controller.js.
