### ISSUE TITLE
Koop not recognizing the existence of the z value

### ISSUE THREAD

**Issue by emilianoMBemt** [koopjs/koop-core#153]
I'm trying to send geo data to arcgis utilizing my own custom Koop provider, however even though the resulting query recognizes the z value of a POINTZ and prints it as such in the geometry, the "hasZ" field of the overall query is still "false". I've looked around the docs but I have not found any way to manually change it to "true" either. Is there a way to fix this issue?

Pictures for more context:
![image](https://user-images.githubusercontent.com/107888878/182420731-737fe9ae-a387-4a31-81e5-1d4bd22f84c2.png)
![image](https://user-images.githubusercontent.com/107888878/182421052-6d38b447-85e9-47e5-be26-89ece55ce52c.png)

**Comment by rgwozdz** [comment]
@emilianoMBemt - thank you for reaching out with this issue.  Looks like this is a current limitation of [FeatureServer](https://github.com/koopjs/FeatureServer); I'll open an issue there.

**Comment by rgwozdz** [comment]
https://github.com/koopjs/FeatureServer/pull/238

**Comment by rgwozdz** [comment]
Feature server has been updated now to support this.  When you create the geojson in your provider, add a `metadata.haz` property to it.

```js
const geojson = {
  metadata: {
    hasZ: true,
    // other metadata
  },
  // other geojson properties
}
```
