### ISSUE TITLE
Just a thought Koopjs + AWS API Gateway + Lambda

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-core#62]
Has anyone tested AWS API Gateways with Koop and Lambda. Seems serverless might actually be a reality at some point.  This would be extremely powerful for multiple reasons, one is it would allow you to scale unique authentication per service or per group of services.

I am going to do some work in this space and report back what I have found.

**Comment by daniel-zeiler** [comment]
did you find anything
